export const ADD_DATASET = "ADD_DATASET";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const DELETE_VARIABLE= "DELETE_VARIABLE";
export const ADD_HINTS = "ADD_HINTS";
export const SET_DATASET = "SET_DATASET";
export const DELETE_ALL_DATASET = "DELETE_ALL_DATASET";