export const ADD_VARIABILE = "ADD_VARIABILE";
export const ADD_MESSAGGIO = "ADD_MESSAGGIO";
export const EDIT_MESSAGGIO = "EDIT_MESSAGGIO";
export const CLEAR_MESSAGGI = "CLEAR_MESSAGGI";
export const DELETE_VARIABLE= "DELETE_VARIABLE";
export const ADD_HINTS = "ADD_HINTS";